### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by xubangwu** [gengshan-y/rigidmask#5]
Hello! Thank you for the training code. But I find some problems. Firstly, in the train code , we should  replace the 'modela' with the 'mode' in the 400 line. Secondly, I do not find the 'max_epo' in the code except for the 503 line. Lastly the pre-trained optical flow and expansion network provided are the same whether train on synthetic dataset or on synthetic dataset + KITTI.

**Comment by gengshan-y** [comment]
Thanks for letting me know, the link to the kitti pretrained weights is updated. The first two issues wouldn't affect functionality of the code and I removed them.
